<?php
require_once __DIR__ . '/config.php';

// If user is already logged in, check if they have a plan and redirect
if (isset($_SESSION['user_id'])) {
    require_once __DIR__ . '/db.php';
    $stmt = $pdo->prepare("SELECT id FROM plans WHERE user_id = ? ORDER BY id DESC LIMIT 1");
    $stmt->execute([$_SESSION['user_id']]);
    if ($stmt->fetch()) {
        header("Location: dashboard.php");
    } else {
        header("Location: setup_plan.php");
    }
    exit;
}

$error = $_SESSION['auth_error'] ?? null;
$active_tab = $_SESSION['active_tab'] ?? 'login';

// Clean up session messages
unset($_SESSION['auth_error']);
unset($_SESSION['active_tab']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BreakFree | Personal Adaptive AI De-Addiction Coach</title>
    <link rel="stylesheet" href="style.css">
    <meta name="description" content="Overcome addictions (smoking, alcohol, screen time) with a personalized plan generated by AI and guided by a personal adaptive coach.">
</head>
<body class="text-center">
    <div class="gradient-bg-glow"></div>
    
    <div class="app-container" style="display: flex; flex-direction: column; justify-content: center; align-items: center; min-height: 100vh;">
        
        <div class="mb-4">
            <a href="index.php" class="logo-area" style="justify-content: center; margin-bottom: 0.5rem;">
                <span class="logo-icon">🌿</span>
                <span class="logo-text">Break<span class="logo-span">Free</span></span>
            </a>
            <p style="color: var(--text-muted); font-size: 1.1rem; max-width: 460px; margin: 0 auto 1.5rem;">
                Overcome habits. Reclaim your time, health, and freedom with personalized adaptive AI coaching.
            </p>
        </div>

        <div class="auth-container">
            <!-- Tabs -->
            <div class="status-toggle" style="margin-bottom: 1.5rem;">
                <button class="toggle-btn <?php echo $active_tab === 'login' ? 'active clean' : ''; ?>" id="tab-login-btn" onclick="switchTab('login')">Log In</button>
                <button class="toggle-btn <?php echo $active_tab === 'register' ? 'active clean' : ''; ?>" id="tab-register-btn" onclick="switchTab('register')">Sign Up</button>
            </div>

            <!-- Error Alerts -->
            <?php if ($error): ?>
                <div class="alert alert-danger" id="auth-alert"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>

            <!-- Login Form -->
            <form id="login-form" action="auth.php?action=login" method="POST" style="display: <?php echo $active_tab === 'login' ? 'block' : 'none'; ?>;">
                <h1 style="display:none">Log In to BreakFree</h1>
                <div class="form-group" style="text-align: left;">
                    <label for="login-username">Username</label>
                    <input type="text" id="login-username" name="username" class="form-control" placeholder="Enter your username" required>
                </div>
                <div class="form-group" style="text-align: left;">
                    <label for="login-password">Password</label>
                    <input type="password" id="login-password" name="password" class="form-control" placeholder="Enter your password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-4" id="login-submit-btn">Continue to Dashboard</button>
            </form>

            <!-- Register Form -->
            <form id="register-form" action="auth.php?action=register" method="POST" style="display: <?php echo $active_tab === 'register' ? 'block' : 'none'; ?>;">
                <h1 style="display:none">Sign Up for BreakFree</h1>
                <div class="form-group" style="text-align: left;">
                    <label for="reg-username">Username</label>
                    <input type="text" id="reg-username" name="username" class="form-control" placeholder="Choose a username" required>
                </div>
                <div class="form-group" style="text-align: left;">
                    <label for="reg-password">Password</label>
                    <input type="password" id="reg-password" name="password" class="form-control" placeholder="Min. 6 characters" required>
                </div>
                <div class="form-row">
                    <div class="form-group" style="text-align: left;">
                        <label for="reg-age">Age</label>
                        <input type="number" id="reg-age" name="age" class="form-control" min="12" max="120" placeholder="Your age" required>
                    </div>
                    <div class="form-group" style="text-align: left;">
                        <label for="reg-gender">Gender</label>
                        <select id="reg-gender" name="gender" class="form-control" required>
                            <option value="" disabled selected>Select</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Non-binary">Non-binary</option>
                            <option value="Prefer not to say">Prefer not to say</option>
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-teal btn-block mt-4" id="register-submit-btn">Create Free Account</button>
            </form>
        </div>

        <div style="margin-top: 2rem; color: var(--text-dark); font-size: 0.85rem;">
            Your recovery is private. Data is stored securely and processed anonymously.
        </div>
    </div>

    <script>
        function switchTab(tab) {
            const loginForm = document.getElementById('login-form');
            const registerForm = document.getElementById('register-form');
            const loginBtn = document.getElementById('tab-login-btn');
            const registerBtn = document.getElementById('tab-register-btn');
            const alertBox = document.getElementById('auth-alert');
            
            if (alertBox) {
                alertBox.style.display = 'none';
            }

            if (tab === 'login') {
                loginForm.style.display = 'block';
                registerForm.style.display = 'none';
                loginBtn.classList.add('active', 'clean');
                registerBtn.classList.remove('active', 'clean');
            } else {
                loginForm.style.display = 'none';
                registerForm.style.display = 'block';
                registerBtn.classList.add('active', 'clean');
                loginBtn.classList.remove('active', 'clean');
            }
        }
    </script>
</body>
</html>
